# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Concise"
license = "MIT"
licenselink = "https://github.com/figueredo/concise/blob/master/LICENSE"
description = "A concise hugo theme"
homepage = "https://github.com/figueredo/concise"
tags = []
features = []
min_version = "0.71"

[author]
  name = "Thiago Cardoso, Larissa Tollstadius"
  homepage = ""
